services:
    nginx-service:
        image: nginx:stable-alpine
        container_name: nginx-container
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/project
            - ./default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php81-service
            - mysql8-service
        networks:
            - nginx-php81-mysql8
    php81-service:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php81-container
        ports:
            - "9000:9000"
        volumes:
            - .:/var/www/project
        networks:
            - nginx-php81-mysql8
    mysql8-service:
        image: mysql:8
        container_name: mysql8-container
        ports:
            - "3306:3306"
        volumes:
            - ./var/mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: systeme
            MYSQL_ROOT_PASSWORD: systeme
            MYSQL_USER: systeme
            MYSQL_PASSWORD: systeme
        restart: always # always restart unless stopped manually
        networks:
            - nginx-php81-mysql8
networks:
    nginx-php81-mysql8: