### Calculate Price
POST http://localhost:8080/calculate-price
Accept: application/json
Content-Type: application/json

{
  "product": 1,
  "taxNumber": "FRDF123456789",
  "couponCode": "F15"
}

### Execute Purchase
POST http://localhost:8080/purchase
Accept: application/json
Content-Type: application/json

{
  "product": 1,
  "taxNumber": "FRDF123456789",
  "couponCode": "F15",
  "paymentProcessor": "paypal"
}
